### ISSUE TITLE
Obtaining a measure or measures of Sufficient Dimension Reduction for downstream tasks?

### ISSUE THREAD

**Issue by adeldaoud** [stat4reg/SDRcausal#3]
@aminGhasempour @stat4reg  We are in a setting where we are using text for causal inference, and thus we are using a high-dimensional sparse document-term matrix (10 000 cases and 130 000 covariates). We are seeking to (1) reduce these 130 000 covariates to a low-dimensional matrix based on their influence on the treatment. For this the Sufficient Dimension Reduction seems useful. Then, (2) we want to use different modeling frameworks (most notably tmle3 and the generalized random forest) to estimate the outcome model, using the SDR metric. Is there a way to obtain a measure or measures of Sufficient Dimension Reduction for downstream tasks? I went over the documentation in the following article, but it was not clear to me how capture such a measure (Ghasempour, M. and de Luna, X. (2021). SDRcausal: an R package for causal inference based on sufficient dimension reduction. arXiv:2105.02499).

**Comment by aminGhasempour** [comment]
Hi,
thank you for your question and interest in our package.

The package provides as output:
  -a one or two dimensional projection of the covariates given as input (alpha_hat) when looking how the covariates explain treatment
  - a one or two dimensional projection of the covariates given as input (beta1_hat) when looking how the covariates explain outcome for those treated
- a one or two dimensional projection of the covariates given as input (beta0_hat) when looking how the covariates explain outcome for those not treated

You can use these for downstream tasks as you mention. 

Let us know if something is unclear.

Best wishes,

Xavier and Mohammad
